version: '3.8'

services:
  postgres:
    image: postgres:17.4-alpine3.21
    container_name: book_rental_postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-book_rental}
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - book_rental_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  book_rental_network:
    driver: bridge
