package controllers

import (
	"bytes"
	"encoding/json"
	"errors"
	"net/http"
	"net/http/httptest"
	"testing"
	"time"

	"github.com/SimpleBookRental/backend/internal/mocks"
	"github.com/SimpleBookRental/backend/internal/models"
	"github.com/gin-gonic/gin"
	"github.com/stretchr/testify/assert"
	"go.uber.org/mock/gomock"
)

// This file uses mocks generated by mockgen

func setupUserController(t *testing.T) (*gin.Engine, *mocks.MockUserServiceInterface, *mocks.MockTokenRepositoryInterface) {
	gin.SetMode(gin.TestMode)
	router := gin.Default()
	ctrl := gomock.NewController(t)
	mockService := mocks.NewMockUserServiceInterface(ctrl)
	mockTokenRepo := mocks.NewMockTokenRepositoryInterface(ctrl)
	controller := &UserController{
		userService: mockService,
		tokenRepo:   mockTokenRepo,
	}

	// Setup routes
	v1 := router.Group("/api/v1")
	{
		v1.POST("/users", controller.Create)
		v1.GET("/users", controller.GetAll)
		v1.GET("/users/:id", controller.GetByID)
		v1.PUT("/users/:id", controller.Update)
		v1.DELETE("/users/:id", controller.Delete)
		v1.POST("/login", controller.Login)
	}

	return router, mockService, mockTokenRepo
}

func TestUserController_Create(t *testing.T) {
	// Setup
	router, mockService, _ := setupUserController(t)

	userCreate := &models.UserCreate{
		Name:     "Test User",
		Email:    "test@example.com",
		Password: "password123",
	}

	user := &models.User{
		ID:       "test-id",
		Name:     userCreate.Name,
		Email:    userCreate.Email,
		Password: "hashed_password",
	}

	// Expectations
	mockService.EXPECT().Create(gomock.AssignableToTypeOf(&models.UserCreate{})).Return(user, nil)

	// Create request
	body, _ := json.Marshal(userCreate)
	req, _ := http.NewRequest("POST", "/api/v1/users", bytes.NewBuffer(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()

	// Perform request
	router.ServeHTTP(w, req)

	// Assert
	assert.Equal(t, http.StatusCreated, w.Code)
	var response map[string]interface{}
	json.Unmarshal(w.Body.Bytes(), &response)
	assert.Equal(t, true, response["success"])
	assert.Equal(t, "User created successfully", response["message"])

	// Verify expectations handled by gomock controller
}

func TestUserController_Create_InvalidRequest(t *testing.T) {
	// Setup
	router, _, _ := setupUserController(t)

	// Invalid request (missing required fields)
	userCreate := map[string]interface{}{
		"name": "Test User",
		// Missing email and password
	}

	// Create request
	body, _ := json.Marshal(userCreate)
	req, _ := http.NewRequest("POST", "/api/v1/users", bytes.NewBuffer(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()

	// Perform request
	router.ServeHTTP(w, req)

	// Assert
	assert.Equal(t, http.StatusBadRequest, w.Code)
	var response map[string]interface{}
	json.Unmarshal(w.Body.Bytes(), &response)
	assert.Equal(t, false, response["success"])
	assert.Equal(t, "Invalid request body", response["message"])

	// No expectations to verify as the service should not be called
}

func TestUserController_Create_ServiceError(t *testing.T) {
	// Setup
	router, mockService, _ := setupUserController(t)

	userCreate := &models.UserCreate{
		Name:     "Test User",
		Email:    "test@example.com",
		Password: "password123",
	}

	// Expectations
	mockService.EXPECT().Create(gomock.AssignableToTypeOf(&models.UserCreate{})).Return(nil, errors.New("service error"))

	// Create request
	body, _ := json.Marshal(userCreate)
	req, _ := http.NewRequest("POST", "/api/v1/users", bytes.NewBuffer(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()

	// Perform request
	router.ServeHTTP(w, req)

	// Assert
	assert.Equal(t, http.StatusBadRequest, w.Code)
	var response map[string]interface{}
	json.Unmarshal(w.Body.Bytes(), &response)
	assert.Equal(t, false, response["success"])
	assert.Equal(t, "Failed to create user", response["message"])

	// Verify expectations handled by gomock controller
}

func TestUserController_GetAll(t *testing.T) {
	// Setup
	router, mockService, _ := setupUserController(t)

	users := []models.User{
		{
			ID:    "user-1",
			Name:  "User 1",
			Email: "user1@example.com",
		},
		{
			ID:    "user-2",
			Name:  "User 2",
			Email: "user2@example.com",
		},
	}

	// Expectations
	mockService.EXPECT().GetAll().Return(users, nil)

	// Create request
	req, _ := http.NewRequest("GET", "/api/v1/users", nil)
	w := httptest.NewRecorder()

	// Perform request
	router.ServeHTTP(w, req)

	// Assert
	assert.Equal(t, http.StatusOK, w.Code)
	var response map[string]interface{}
	json.Unmarshal(w.Body.Bytes(), &response)
	assert.Equal(t, true, response["success"])
	assert.Equal(t, "Users retrieved successfully", response["message"])

	// Verify expectations handled by gomock controller
}

func TestUserController_GetAll_ServiceError(t *testing.T) {
	// Setup
	router, mockService, _ := setupUserController(t)

	// Expectations
	mockService.EXPECT().GetAll().Return([]models.User{}, errors.New("service error"))

	// Create request
	req, _ := http.NewRequest("GET", "/api/v1/users", nil)
	w := httptest.NewRecorder()

	// Perform request
	router.ServeHTTP(w, req)

	// Assert
	assert.Equal(t, http.StatusInternalServerError, w.Code)
	var response map[string]interface{}
	json.Unmarshal(w.Body.Bytes(), &response)
	assert.Equal(t, false, response["success"])
	assert.Equal(t, "Failed to retrieve users", response["message"])

	// Verify expectations handled by gomock controller
}

func TestUserController_GetByID(t *testing.T) {
	// Setup
	router, mockService, _ := setupUserController(t)

	userID := "123e4567-e89b-12d3-a456-426614174001"
	user := &models.User{
		ID:    userID,
		Name:  "Test User",
		Email: "test@example.com",
	}

	// Expectations
	mockService.EXPECT().GetByID(userID).Return(user, nil)

	// Create request
	req, _ := http.NewRequest("GET", "/api/v1/users/"+userID, nil)
	w := httptest.NewRecorder()

	// Perform request
	router.ServeHTTP(w, req)

	// Assert
	assert.Equal(t, http.StatusOK, w.Code)
	var response map[string]interface{}
	json.Unmarshal(w.Body.Bytes(), &response)
	assert.Equal(t, true, response["success"])
	assert.Equal(t, "User retrieved successfully", response["message"])

	// Verify expectations handled by gomock controller
}

func TestUserController_GetByID_ServiceError(t *testing.T) {
	// Setup
	router, mockService, _ := setupUserController(t)

	userID := "123e4567-e89b-12d3-a456-426614174001"

	// Expectations
	mockService.EXPECT().GetByID(userID).Return(nil, errors.New("service error"))

	// Create request
	req, _ := http.NewRequest("GET", "/api/v1/users/"+userID, nil)
	w := httptest.NewRecorder()

	// Perform request
	router.ServeHTTP(w, req)

	// Assert
	assert.Equal(t, http.StatusNotFound, w.Code)
	var response map[string]interface{}
	json.Unmarshal(w.Body.Bytes(), &response)
	assert.Equal(t, false, response["success"])
	assert.Equal(t, "service error", response["message"])

	// Verify expectations handled by gomock controller
}

func TestUserController_Update(t *testing.T) {
	// Setup
	router, mockService, _ := setupUserController(t)

	userID := "123e4567-e89b-12d3-a456-426614174001"
	userUpdate := &models.UserUpdate{
		Name:     "Updated User",
		Email:    "updated@example.com",
		Password: "newpassword123",
	}

	updatedUser := &models.User{
		ID:       userID,
		Name:     userUpdate.Name,
		Email:    userUpdate.Email,
		Password: "hashed_password",
	}

	// Expectations
	mockService.EXPECT().Update(userID, gomock.AssignableToTypeOf(&models.UserUpdate{})).Return(updatedUser, nil)

	// Create request
	body, _ := json.Marshal(userUpdate)
	req, _ := http.NewRequest("PUT", "/api/v1/users/"+userID, bytes.NewBuffer(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()

	// Perform request
	router.ServeHTTP(w, req)

	// Assert
	assert.Equal(t, http.StatusOK, w.Code)
	var response map[string]interface{}
	json.Unmarshal(w.Body.Bytes(), &response)
	assert.Equal(t, true, response["success"])
	assert.Equal(t, "User updated successfully", response["message"])

	// Verify expectations handled by gomock controller
}

func TestUserController_Update_InvalidRequest(t *testing.T) {
	// Setup
	router, _, _ := setupUserController(t)

	userID := "test-id"

	// Invalid request (invalid JSON)
	req, _ := http.NewRequest("PUT", "/api/v1/users/"+userID, bytes.NewBuffer([]byte("invalid json")))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()

	// Perform request
	router.ServeHTTP(w, req)

	// Assert
	assert.Equal(t, http.StatusBadRequest, w.Code)
	var response map[string]interface{}
	json.Unmarshal(w.Body.Bytes(), &response)
	assert.Equal(t, false, response["success"])
	assert.Equal(t, "Invalid request body", response["message"])

	// No expectations to verify as the service should not be called
}

func TestUserController_Update_ServiceError(t *testing.T) {
	// Setup
	router, mockService, _ := setupUserController(t)

	userID := "123e4567-e89b-12d3-a456-426614174001"
	userUpdate := &models.UserUpdate{
		Name:     "Updated User",
		Email:    "updated@example.com",
		Password: "newpassword123",
	}

	// Expectations
	mockService.EXPECT().Update(userID, gomock.AssignableToTypeOf(&models.UserUpdate{})).Return(nil, errors.New("service error"))

	// Create request
	body, _ := json.Marshal(userUpdate)
	req, _ := http.NewRequest("PUT", "/api/v1/users/"+userID, bytes.NewBuffer(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()

	// Perform request
	router.ServeHTTP(w, req)

	// Assert
	assert.Equal(t, http.StatusBadRequest, w.Code)
	var response map[string]interface{}
	json.Unmarshal(w.Body.Bytes(), &response)
	assert.Equal(t, false, response["success"])
	assert.Equal(t, "Failed to update user", response["message"])

	// Verify expectations handled by gomock controller
}

func TestUserController_Delete(t *testing.T) {
	// Setup
	router, mockService, _ := setupUserController(t)

	userID := "123e4567-e89b-12d3-a456-426614174001"

	// Expectations
	mockService.EXPECT().Delete(userID).Return(nil)

	// Create request
	req, _ := http.NewRequest("DELETE", "/api/v1/users/"+userID, nil)
	w := httptest.NewRecorder()

	// Perform request
	router.ServeHTTP(w, req)

	// Assert
	assert.Equal(t, http.StatusOK, w.Code)
	var response map[string]interface{}
	json.Unmarshal(w.Body.Bytes(), &response)
	assert.Equal(t, true, response["success"])
	assert.Equal(t, "User deleted successfully", response["message"])

	// Verify expectations handled by gomock controller
}

func TestUserController_Delete_ServiceError(t *testing.T) {
	// Setup
	router, mockService, _ := setupUserController(t)

	userID := "123e4567-e89b-12d3-a456-426614174001"

	// Expectations
	mockService.EXPECT().Delete(userID).Return(errors.New("service error"))

	// Create request
	req, _ := http.NewRequest("DELETE", "/api/v1/users/"+userID, nil)
	w := httptest.NewRecorder()

	// Perform request
	router.ServeHTTP(w, req)

	// Assert
	assert.Equal(t, http.StatusBadRequest, w.Code)
	var response map[string]interface{}
	json.Unmarshal(w.Body.Bytes(), &response)
	assert.Equal(t, false, response["success"])
	assert.Equal(t, "Failed to delete user", response["message"])

	// Verify expectations handled by gomock controller
}

func TestUserController_Login(t *testing.T) {
	// Setup
	router, mockService, mockTokenRepo := setupUserController(t)

	userLogin := &models.UserLogin{
		Email:    "test@example.com",
		Password: "password123",
	}

	loginResponse := &models.LoginResponse{
		User: &models.User{
			ID:    "test-id",
			Name:  "Test User",
			Email: userLogin.Email,
		},
		AccessToken:  "access-token",
		RefreshToken: "refresh-token",
		ExpiresAt:    time.Now().Unix(),
	}

	// Expectations
	mockService.EXPECT().Login(gomock.AssignableToTypeOf(&models.UserLogin{}), mockTokenRepo).Return(loginResponse, nil)

	// Create request
	body, _ := json.Marshal(userLogin)
	req, _ := http.NewRequest("POST", "/api/v1/login", bytes.NewBuffer(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()

	// Perform request
	router.ServeHTTP(w, req)

	// Assert
	assert.Equal(t, http.StatusOK, w.Code)
	var response map[string]interface{}
	json.Unmarshal(w.Body.Bytes(), &response)
	assert.Equal(t, true, response["success"])
	assert.Equal(t, "Login successful", response["message"])

	// Verify expectations handled by gomock controller
}

func TestUserController_Login_InvalidRequest(t *testing.T) {
	// Setup
	router, _, _ := setupUserController(t)

	// Invalid request (missing required fields)
	userLogin := map[string]interface{}{
		"email": "test@example.com",
		// Missing password
	}

	// Create request
	body, _ := json.Marshal(userLogin)
	req, _ := http.NewRequest("POST", "/api/v1/login", bytes.NewBuffer(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()

	// Perform request
	router.ServeHTTP(w, req)

	// Assert
	assert.Equal(t, http.StatusBadRequest, w.Code)
	var response map[string]interface{}
	json.Unmarshal(w.Body.Bytes(), &response)
	assert.Equal(t, false, response["success"])
	assert.Equal(t, "Invalid request body", response["message"])

	// No expectations to verify as the service should not be called
}

func TestUserController_Login_ServiceError(t *testing.T) {
	// Setup
	router, mockService, mockTokenRepo := setupUserController(t)

	userLogin := &models.UserLogin{
		Email:    "test@example.com",
		Password: "password123",
	}

	// Expectations
	mockService.EXPECT().Login(gomock.AssignableToTypeOf(&models.UserLogin{}), mockTokenRepo).Return(nil, errors.New("service error"))

	// Create request
	body, _ := json.Marshal(userLogin)
	req, _ := http.NewRequest("POST", "/api/v1/login", bytes.NewBuffer(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()

	// Perform request
	router.ServeHTTP(w, req)

	// Assert
	assert.Equal(t, http.StatusBadRequest, w.Code)
	var response map[string]interface{}
	json.Unmarshal(w.Body.Bytes(), &response)
	assert.Equal(t, false, response["success"])
	assert.Equal(t, "Login failed", response["message"])

	// Verify expectations handled by gomock controller
}
